name = "deploymentdelete"
main = "./Target/Worker.js"
compatibility_date = "2023-05-18"
node_compat = true
keep_vars = true
send_metrics = false
tsconfig = "./tsconfig.json"
workers_dev = false

[build]
command = "npm run prepublishOnly"
cwd = "."
watch_dir = "./Source"

[dev]
ip = "127.0.0.1"
port = 4001

[placement]
mode = "smart"
